---
output: pdf_document
---
**Comparación de redes de co-expresión derivadas de la interacción entre *Phythophthora infestans* y *Solanum spp***

**Estudiantes:**

1.  Kelly Botero
2.  Juan Henao
3.  Daniel Osorio

**Descripción del problema:**

El tizón tardío es una enfermedad que afecta al tomate y a la papa provocando grandes pérdidas en este tipo de plantas de interés comercial por lo cual está asociado con las mayores pérdidas en el sector productivo, lo que pone en riesgo las políticas de seguridad alimentaria (Sierra, *et al*. 2010).

Este problema de índole fitopatologico es causado por el oomycete *Phytophthora infestans* el cual provoca en las plantas hospederas síntomas tales como la aparición de manchas circulares e irregulares que pueden ser de color café o negro y además en los tubérculos causan lesiones irregulares de color cobre o marrón que pueden propagarse hasta pudrirse por completo (Bush, *et al*. 2012).

Múltiples investigaciones han intentado comprender aspectos moleculares que subyacen la interacción compatible e incompatible entre P. infestans y S. toberosum (Catanzariti, *et al*, 2007). Algunas han utilizado estrategias como expresión génica (Gao, *et al*. 2013) y genómica comparativa (Jones, 2012), que aprovechan los avances en tecnologías genómicas para abordar preguntas de investigación.

*P. infestans* afecta a un amplio rango de hospederos dentro de la familia Solanaceae. En Colombia, la especie de papa amarilla (*Solanum phureja*), es cultivada de manera intensiva y el tizón tardío es la principal fuente de pérdidas y no ha sido posible generar controles efectivos contra el patógeno *P. infestans* debido al poco conocimiento que se posee entre la interacción de estas dos especies a pesar de los esfuerzos por determinar todos los componentes moleculares asociados al patosistema planta-oomycete (Sierra, *et al*. 2010).

**Descripción de los datos**
```{r}
# Librerías requeridas
library("GEOquery")
library("vsn")

# Datos elegidos:
GSE14480<- getGEO("GSE14480")
GSE14480<- GSE14480$GSE14480_series_matrix.txt.gz

# Verificando los datos
head(exprs(GSE14480))

```

**Bibliografía**

**1** Bush, E. A., Rideout, S. L., & Waldenmaier, C. (2012). Late Blight of Tomato and Potato.

**2** Sierra, R., Rodriguez, R. L., Chaves, D., Pinzón, A., Grajales, A., Rojas, A., ... & Restrepo, S. (2010). Discovery of Phytophthora infestans genes expressed in planta through mining of cDNA libraries. PloS one, 5(3).

**3** A.-M. Catanzariti, P. N. Dodds, and J. G. Ellis, “Avirulence proteins from haustoria-forming pathogens,” FEMS Microbiol. Lett., vol. 269, no. 2, pp. 181–188, 2007.

**4** L. Gao, Z. Tu, B. P. Millett, and J. M. Bradeen, “Insights into organ-specific pathogen defense responses in plants: RNA-seq analysis of potato tuber-Phytophthora infestans interactions,” BMC Genomics, vol. 14, no. 1, p. 340, 2013.

**5** R. W. Jones, “Multiple Copies of Genes Encoding XEGIPs are Harbored in an 85-kB Region of the Potato Genome,” Plant Mol. Biol. Report., vol. 30, no. 4, pp. 1040–1046, 2012.